[build]
  functions = "public/netlify/functions"  # Thư mục chứa các Netlify Functions
  publish = "public"  # Thư mục chứa các tài nguyên tĩnh

[build.environment]
  NODE_VERSION = "14"  # Nếu bạn cần chỉ định phiên bản Node.js
